baseURL = 'https://keiji.github.io/bocchi-docs/'
languageCode = 'ja-jp'
title = 'Bocchi Docs'
theme = 'hugo-book'

disablePathToLower = true
enableGitInfo = true

defaultContentLanguage = 'ja'
defaultContentLanguageInSubdir = true

[services.googleAnalytics]
  ID = 'G-XYQDKL8251'

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[languages.ja]
    contentDir = 'content/ja'
    staticDir1 = 'static/ja'
    disabled = false
    languageCode = 'ja'
    languageDirection = 'ltr'
    languageName = 'Japanese'
    title = 'Bocchi Docs'
    weight = 10
[languages.en]
    contentDir = 'content/en'
    staticDir1 = 'static/en'
    disabled = true
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Bocchi Docs'
    weight = 20
